public class AuthenticationResult {
  public static final String OK = 'OK';
  public static final String OK_VALIDATED_AND_REGISTERED = 'OK_VALIDATED_AND_REGISTERED';
  public static final String BAD_OTP = 'BAD_OTP';
  public static final String REPLAYED_OTP = 'REPLAYED_OTP';
  public static final String YUBIKEY_ID_USER_MISMATCH = 'YUBIKEY_ID_USER_MISMATCH';
  public static final String NONCE_MISMATCH = 'NONCE_MISMATCH';
  public static final String USERS_CANNOT_SHARE_THE_SAME_YUBIKEY = 'USERS_CANNOT_SHARE_THE_SAME_YUBIKEY';
  public static final String PACKAGE_NOT_CONFIGURED = 'PACKAGE_NOT_CONFIGURED';
}